# Generated by Django 6.0.4 on 2026-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_rename_saller_post_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='seller',
            new_name='aurthor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
