# Generated by Django 6.0.4 on 2026-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_seller_post_aurthor_rename_name_post_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aurthor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/'),
        ),
    ]
